import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Download, CheckCircle, Copy } from 'lucide-react';
import { useProjectStore } from '../../store/useProjectStore';
import { ZipExporter } from '../../services/exporters/ZipExporter';

export const Step6_Export: React.FC = () => {
  const { generatedProject, apiConfig } = useProjectStore();
  const [isExporting, setIsExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const exporter = new ZipExporter();

  const handleDownload = async () => {
    if (!generatedProject) return;

    setIsExporting(true);
    try {
      await exporter.exportAndDownload(generatedProject);
      setExported(true);
    } catch (error) {
      console.error('Export error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const proxyName = apiConfig.proxyName || 'apigee-proxy';

  const azureDevOpsInstructions = `# Import to Azure DevOps

1. Download the ZIP file: ${proxyName}.zip

2. Extract the ZIP file:
   unzip ${proxyName}.zip
   cd ${proxyName}

3. Initialize Git repository:
   git init
   git add .
   git commit -m "Initial commit - Generated by Apigee React Generator"

4. Create a new repository on Azure DevOps

5. Push to Azure DevOps:
   git remote add origin <your-azure-devops-repo-url>
   git push -u origin master

6. Deploy to Apigee:
   cd src/main/apigee/gateway
   mvn install -Pgoogleapi -Denv=dev1 -Dorg=your-org -Dtoken=your-token
`;

  const fileCount = generatedProject?.files.size || 0;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(azureDevOpsInstructions);
  };

  return (
    <div className="min-h-screen">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Export & Deploy</h1>
        <p className="text-[var(--text-secondary)] text-lg">Download your generated project and deploy to Azure DevOps</p>
      </div>

      <div className="space-y-6">
        {exported && (
          <Alert className="soft-alert success">
            <CheckCircle className="h-4 w-4" />
            <AlertDescription className="font-medium">
              Project exported successfully!
            </AlertDescription>
          </Alert>
        )}

        <div className="soft-card">
          <div className="section-header mb-6">
            <div>
              <h3 className="text-xl">Project: {proxyName}</h3>
              <p className="text-sm text-[var(--text-secondary)] mt-1">Files generated: {fileCount}</p>
            </div>
          </div>

          <Button
            size="lg"
            onClick={handleDownload}
            disabled={isExporting}
            className="soft-button"
          >
            <Download className="mr-2 h-5 w-5" />
            {isExporting ? 'Exporting...' : 'Download ZIP'}
          </Button>
        </div>

        <Accordion type="single" collapsible className="w-full space-y-4">
          <AccordionItem value="azure-devops" className="soft-card border-none">
            <AccordionTrigger className="text-lg font-semibold text-[var(--text-primary)] hover:text-[var(--lavender-600)] px-6">
              Azure DevOps Integration Guide
            </AccordionTrigger>
            <AccordionContent className="px-6 pb-6">
              <div className="space-y-4">
                <p className="text-sm text-[var(--text-secondary)]">
                  Follow these steps to import your generated project into Azure DevOps:
                </p>

                <div className="relative">
                  <Button
                    size="sm"
                    variant="outline"
                    className="absolute top-2 right-2 z-10 soft-button secondary text-xs"
                    onClick={copyToClipboard}
                  >
                    <Copy className="mr-2 h-3 w-3" />
                    Copy
                  </Button>
                  <pre className="bg-[var(--cream-200)] text-[var(--text-primary)] border border-[var(--border-light)] p-4 rounded-2xl overflow-x-auto text-sm font-mono">
                    {azureDevOpsInstructions}
                  </pre>
                </div>
              </div>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="file-structure" className="soft-card border-none">
            <AccordionTrigger className="text-lg font-semibold text-[var(--text-primary)] hover:text-[var(--lavender-600)] px-6">
              Generated Files Structure
            </AccordionTrigger>
            <AccordionContent className="px-6 pb-6">
              <div className="space-y-1 max-h-96 overflow-y-auto">
                {Array.from(generatedProject?.files.keys() || []).sort().map((filePath) => (
                  <div
                    key={filePath}
                    className="py-2 px-3 hover:bg-[var(--lavender-50)] rounded-lg text-sm font-mono border-b border-[var(--border-light)] last:border-0 text-[var(--text-secondary)] transition-colors"
                  >
                    {filePath}
                  </div>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
};
