export default {
  // Common
  common: {
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    add: 'Add',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    settings: 'Settings',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    validate: 'Validate',
    validating: 'Validating...',
    complete: 'Complete',
    enabled: 'Enabled',
    disabled: 'Disabled',
    yes: 'Yes',
    no: 'No',
    or: 'or',
    of: 'of',
    step: 'Step',
    modified: 'modified',
    autoGenerated: 'Auto-generated',
    regenerate: 'Regenerate',
    manuallyModified: 'Manually modified',
    savedAutomatically: 'Saved automatically',
    testConnection: 'Test Connection',
    testing: 'Testing...',
  },

  // App Header
  app: {
    title: 'Apigee Template Generator',
    subtitle: 'Generate professional Apigee API proxies',
    footer: 'Apigee Template Generator - Generate Apigee proxies from OpenAPI specifications',
  },

  // Wizard Navigation
  wizard: {
    steps: {
      configuration: 'Configuration',
      openapi: 'OpenAPI',
      environments: 'Environments',
      generate: 'Generate',
      azureDevOps: 'Azure DevOps',
      export: 'Export',
    },
    progress: 'Step {{current}} of {{total}}',
  },

  // Step 1: API Configuration
  step1: {
    title: 'API Configuration',
    subtitle: 'Configure your API proxy settings',
    sections: {
      proxyNaming: 'Proxy Naming Convention',
      routing: 'Routing Configuration',
      security: 'Security & Limits',
      optional: 'Optional Configuration',
    },
    fields: {
      entity: {
        label: 'Entity',
        placeholder: 'Select',
        tooltip: 'Select the entity type: "elis" for internal APIs or "ext" for external APIs',
        options: {
          elis: 'elis (Internal)',
          ext: 'ext (External)',
        },
      },
      domain: {
        label: 'Domain',
        placeholder: 'finance',
        tooltip: 'Business domain (e.g., finance, hr, supply-chain)',
      },
      backendApps: {
        label: 'Backend Apps',
        placeholder: 'sap-sf',
        tooltip: 'Backend applications separated by hyphens (e.g., sap, salesforce, sap-sf)',
      },
      businessObject: {
        label: 'Business Object',
        placeholder: 'invoice',
        tooltip: 'The main business object this API manages (e.g., invoice, customer, order)',
      },
      version: {
        label: 'Version',
        placeholder: 'v1',
        tooltip: 'API version (e.g., v1, v2)',
      },
      description: {
        label: 'Description',
        placeholder: 'API for managing invoices',
        tooltip: 'A brief description of what this API does',
      },
      proxyBasepath: {
        label: 'Proxy Basepath',
        placeholder: 'customer-api/v1',
        tooltip: 'The base path for your API proxy (e.g., /customer-api/v1)',
        autoGenerated: 'Auto-generated based on proxy name',
      },
      targetPath: {
        label: 'Target Path',
        placeholder: '/v1',
        tooltip: 'The path prefix to add when forwarding requests to the backend',
      },
      authSouthbound: {
        label: 'Southbound Authentication',
        tooltip: 'Authentication method for backend communication',
        options: {
          none: 'None',
          basic: 'Basic Authentication',
          oauth2: 'OAuth2 Client Credentials',
        },
      },
      globalRateLimit: {
        label: 'Global Rate Limit',
        placeholder: '500pm or 100ps',
        tooltip: 'Rate limit for all API calls (e.g., 500pm = 500 per minute, 100ps = 100 per second)',
      },
      mockUrl: {
        label: 'Mock URL',
        placeholder: 'https://stoplight.io/mocks/...',
        tooltip: 'Optional mock server URL for testing (e.g., Stoplight mock URL)',
      },
    },
    proxyName: {
      label: 'Proxy Name',
      format: 'Format: [entity].[domain].[backendApps].[businessObject].[version]',
    },
  },

  // Step 2: OpenAPI Editor
  step2: {
    title: 'OpenAPI Specification',
    subtitle: 'Upload and validate your OpenAPI specification',
    uploadButton: 'Upload JSON/YAML File',
    dragDrop: 'Drag and drop your OpenAPI file here, or click the button above',
    supportedFiles: 'Supports .json, .yaml, .yml files',
    validation: {
      title: 'Validation',
      valid: 'Specification is valid!',
      invalid: 'Specification has errors',
      openApiVersion: 'OpenAPI Version',
      endpointsDetected: 'Endpoints Detected',
      paths: 'Paths',
    },
    placeholder: 'Upload or paste your OpenAPI specification to begin validation',
    errors: {
      invalidFormat: 'Invalid file format. Please upload a JSON or YAML file.',
      parseError: 'Failed to parse the specification. Please check the syntax.',
    },
  },

  // Step 3: Environment Configuration
  step3: {
    title: 'Environment Configuration',
    subtitle: 'Configure target servers and API products for each environment',
    alerts: {
      completeApiConfig: 'Please complete the API configuration in Step 1 first',
      initializing: 'Environments are being initialized...',
      syncMode: 'Sync mode active: Changes in DEV1 will be replicated to other environments',
    },
    tabs: {
      targetServer: 'Target Server Configuration',
      apiProduct: 'API Product Configuration',
      kvm: 'Key-Value Maps (KVM)',
    },
    targetServer: {
      name: 'Target Server Name',
      host: 'Host',
      port: 'Port',
      sslEnabled: 'SSL Enabled',
      autoGenerated: 'Auto-generated based on proxy name',
    },
    apiProduct: {
      name: 'Product Name',
      displayName: 'Display Name',
      description: 'Description',
      approvalType: 'Approval Type',
      auto: 'Auto',
      manual: 'Manual',
    },
    kvm: {
      title: 'Key-Value Maps (KVM)',
      description: 'Manage encrypted key-value storage for backend credentials and configuration',
      name: 'KVM Name',
      encrypted: 'Encrypted',
      encryptedHelp: 'Encrypted (recommended for sensitive data like passwords)',
      entries: 'Key-Value Entries',
      addKvm: 'Add KVM',
      addEntry: 'Add Entry',
      keyPlaceholder: 'Key (e.g., username)',
      valuePlaceholder: 'Value (e.g., admin)',
      namePlaceholder: 'my-backend-credentials',
      noEntries: 'No entries yet. Click "Add Entry" to add key-value pairs.',
      noKvms: 'No KVMs configured. Click "Add KVM" to create a key-value map.',
    },
  },

  // Step 4: Generation
  step4: {
    title: 'Generate Apigee Project',
    subtitle: 'Generate the complete Apigee proxy bundle',
    checklist: {
      title: 'Pre-generation Checklist',
      apiConfig: 'API Configuration (Step 1)',
      openApiSpec: 'OpenAPI Specification (Step 2)',
    },
    ready: {
      title: 'Ready to generate your Apigee proxy',
      description: 'Click the button below to generate the complete project structure',
    },
    notReady: {
      title: 'Complete the checklist to enable generation',
      description: 'Please complete all required steps before generating',
    },
    button: 'Generate Project',
    generating: 'Generating...',
    steps: {
      initializing: 'Initializing generation...',
      eclipse: 'Generating Eclipse files...',
      maven: 'Generating Maven POMs...',
      proxy: 'Generating proxy configuration...',
      proxyConfig: 'Generating proxy configuration...',
      flows: 'Generating flows from OpenAPI...',
      policies: 'Generating policies...',
      targets: 'Generating target endpoints...',
      targetEndpoints: 'Generating target endpoints...',
      environments: 'Generating environment configurations...',
      envConfig: 'Generating environment configurations...',
      finalizing: 'Finalizing project structure...',
      complete: 'Generation complete!',
    },
    success: 'Project generated successfully!',
    errors: {
      configIncomplete: 'API configuration is incomplete. Please fill in all required fields in Step 1 (Configuration)',
      openApiMissing: 'OpenAPI specification is missing. Please upload and validate your OpenAPI spec in Step 2 (OpenAPI)',
      both: 'Please complete the API configuration in Step 1 and upload/validate your OpenAPI specification in Step 2',
    },
  },

  // Step 5: Azure DevOps
  step5: {
    title: 'Azure DevOps Integration',
    subtitle: 'Configure Azure DevOps to automatically create a repository and push your generated code',
    enableIntegration: 'Enable Azure DevOps Integration',
    disabledMessage: 'Enable Azure DevOps integration to push your generated project to a repository',
    sections: {
      config: 'Azure DevOps Configuration',
      repository: 'Repository',
      options: 'Options',
    },
    config: {
      organization: 'Organization:',
      project: 'Project:',
      branch: 'Branch:',
      pat: 'PAT:',
      configured: 'Configured',
      notConfigured: 'Not configured',
    },
    modifySettings: 'Modify Settings',
    openSettings: 'Open Settings',
    notConfiguredAlert: 'Azure DevOps settings are not configured. Please configure your organization, project, and PAT in the settings.',
    repository: {
      name: 'Repository Name',
      required: 'Repository Name *',
      tooltip: 'The name of the repository to create or use in Azure DevOps',
    },
    options: {
      createRepo: 'Create repository automatically if it doesn\'t exist',
      autoPush: 'Automatically push code after project generation',
      createPipelines: 'Create CI/CD pipelines (Coming soon)',
    },
    push: {
      button: 'Push to Azure DevOps',
      pushing: 'Pushing to Azure DevOps...',
      progress: 'Pushing batch {{current}} of {{total}} ({{files}} files total)',
      success: 'Successfully pushed to Azure DevOps!',
      openRepo: 'Open Repository in Azure DevOps',
    },
    generateFirst: 'Generate your Apigee project first (Step 4) before pushing to Azure DevOps',
    projectReady: 'Project Generated! You can now push your code to Azure DevOps.',
  },

  // Step 6: Export
  step6: {
    title: 'Export & Deploy',
    subtitle: 'Download your generated project and deploy to Azure DevOps',
    download: {
      button: 'Download ZIP',
      exporting: 'Exporting...',
    },
    projectInfo: {
      project: 'Project:',
      filesGenerated: 'Files generated:',
    },
    sections: {
      azureGuide: 'Azure DevOps Integration Guide',
      fileStructure: 'Generated Files Structure',
    },
  },

  // Settings Modal
  settings: {
    title: 'Settings',
    tabs: {
      templates: 'Templates',
      azureDevOps: 'Azure DevOps',
    },
  },

  // Azure DevOps Settings
  azureSettings: {
    title: 'Azure DevOps Configuration',
    description: 'These settings are automatically saved in your browser.',
    repoNameNote: 'The repository name is configured per project in Step 5.',
    fields: {
      organization: {
        label: 'Organization',
        placeholder: 'my-organization',
        help: 'Your Azure DevOps organization name (visible in the URL)',
      },
      project: {
        label: 'Project',
        placeholder: 'my-project',
        help: 'The Azure DevOps project where repositories will be created',
      },
      pat: {
        label: 'Personal Access Token (PAT)',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        help: 'A PAT with "Code (Read & Write)" permissions',
      },
      defaultBranch: {
        label: 'Default Branch',
        placeholder: 'main',
        help: 'The default branch for new repositories (main, master, develop...)',
      },
    },
    testConnection: 'Test Connection',
    testing: 'Testing...',
    testSuccess: 'Connection successful! Settings are valid.',
    testFailure: 'Connection failed. Please check your settings.',
    missingFields: 'Please fill in the organization and token.',
    testError: 'Error while testing connection.',
  },

  // Template Manager
  templates: {
    title: 'Template Files',
    loading: 'Loading templates...',
    exportZip: 'Export ZIP',
    importZip: 'Import ZIP',
    modified: 'modified',
    selectToEdit: 'Select a template to edit',
  },

  // Language
  language: {
    label: 'Language',
    en: 'English',
    fr: 'French',
  },
};
