// Help content for each canvas card

export const openAPIHelpContent = {
  title: 'OpenAPI Specification',
  description: 'Import your OpenAPI (Swagger) file to start configuration. The application automatically analyzes the file and pre-fills several configuration fields.',
  steps: [
    { number: 1, text: 'Drag and drop your OpenAPI file (.json or .yaml) into the designated area, or click to browse your files.' },
    { number: 2, text: 'The Monaco editor displays the file content. You can edit it directly if needed.' },
    { number: 3, text: 'Click "Parse & Auto-fill" to validate and automatically extract information.', isAutoGenerated: true },
    { number: 4, text: 'Review the detected values displayed at the bottom of the card.' },
  ],
  autoGeneratedFields: [
    {
      name: 'Authentication Type',
      description: 'Detected from the "securitySchemes" in your OpenAPI spec. Supports Basic Auth, OAuth2 Client Credentials, and API Key.',
      format: 'Basic | OAuth2-ClientCredentials | ApiKey | None',
    },
    {
      name: 'Target Path',
      description: 'The base path extracted from the first defined server. This path will be used to route requests to your backend.',
      example: '/api/v1',
    },
    {
      name: 'Servers per Environment',
      description: 'Server URLs are mapped to environments (dev, staging, prod) based on detected naming conventions.',
    },
  ],
  manualFields: [],
  tips: [
    'Use an OpenAPI 3.0+ specification for better automatic detection.',
    'Ensure your spec contains "servers" with URLs for your different environments.',
    'The "securitySchemes" enable automatic authentication type detection.',
  ],
};

export const proxyConfigHelpContent = {
  title: 'API Proxy',
  description: 'Configure the naming convention and authentication settings for your Apigee proxy. The proxy name is automatically generated according to the established convention.',
  steps: [
    { number: 1, text: 'Select the entity (elis for internal, ext for external).' },
    { number: 2, text: 'Fill in the Domain, Backend Apps, Business Object, and Version fields using kebab-case format.' },
    { number: 3, text: 'The proxy name and basepath are automatically generated from the fields above.', isAutoGenerated: true },
    { number: 4, text: 'Configure southbound authentication if your backend requires authentication.' },
  ],
  autoGeneratedFields: [
    {
      name: 'Proxy Basepath',
      description: 'Automatically generated from the Business Object and Version fields you enter. Format: /{businessObject}/{version}. You can override this value if needed.',
      format: '/{businessObject}/{version}',
      example: '/invoices/v1',
    },
    {
      name: 'Auth Southbound',
      description: 'Pre-filled if a "securityScheme" is defined in your OpenAPI. Defines how Apigee authenticates with your backend.',
      format: 'None | Basic | OAuth2-ClientCredentials | ApiKey',
    },
    {
      name: 'Proxy Name (Preview)',
      description: 'Automatically calculated from the 5 naming components you enter.',
      example: 'elis.finance.erp-sap.invoices.v1',
    },
  ],
  manualFields: [
    {
      name: 'Entity',
      description: 'Identifies whether the API is internal (elis) or external (ext). Used in the proxy naming convention.',
      format: 'elis | ext',
    },
    {
      name: 'Domain',
      description: 'The business domain to which this API belongs (e.g., finance, supply-chain, hr).',
      format: 'kebab-case',
      example: 'finance',
    },
    {
      name: 'Backend Apps',
      description: 'The backend application that is the data source. Can be compound (erp-sap).',
      format: 'kebab-case',
      example: 'erp-sap',
    },
    {
      name: 'Business Object',
      description: 'The main business object exposed by this API.',
      format: 'kebab-case',
      example: 'invoices',
    },
    {
      name: 'Version',
      description: 'The major version of the API.',
      format: 'v{number}',
      example: 'v1',
    },
    {
      name: 'Global Rate Limit',
      description: 'Limits the number of requests per minute (pm) or per second (ps). Default: 100pm.',
      format: '{number}pm or {number}ps',
      example: '100pm',
    },
  ],
  tips: [
    'Use explicit kebab-case names to facilitate maintenance.',
    'The basepath is auto-generated as /{businessObject}/{version}. Override it only if needed.',
    'The global rate limit (default 100pm) applies to all requests, regardless of the product.',
  ],
};

export const apiProductsHelpContent = {
  title: 'API Products',
  description: 'Configure API products for each environment. An API product defines which paths are accessible and with what restrictions. You can have multiple products per environment to segment access.',
  steps: [
    { number: 1, text: 'Select the environment tab to configure (dev1, uat1, etc.).' },
    { number: 2, text: 'Use "Auto-generate from OpenAPI" to automatically create products based on your paths.', isAutoGenerated: true },
    { number: 3, text: 'Or click "Add Product" to manually create a new product.' },
    { number: 4, text: 'Configure the authorized paths, approval type, and access level for each product.' },
  ],
  autoGeneratedFields: [
    {
      name: 'Product Name',
      description: 'Automatically generated from the proxy name and environment. Format: proxyName.environment or proxyName.groupPrefix.environment.',
      example: 'elis.finance.erp-sap.invoices.v1.customers.dev1',
    },
    {
      name: 'Display Name',
      description: 'Human-readable name generated from the business object and version.',
      example: 'invoices-v1',
    },
    {
      name: 'Description',
      description: 'Automatically generated from the "info.description" field in your OpenAPI or from proxy metadata.',
    },
    {
      name: 'Authorized Paths',
      description: 'By default, includes all root paths detected in the OpenAPI with wildcard (/**). The auto-generate function groups paths by common prefix.',
      example: '/customers/**, /orders/**',
    },
  ],
  manualFields: [
    {
      name: 'Approval Type',
      description: 'Auto: developers can use the product immediately. Manual: requires admin approval.',
      format: 'auto | manual',
    },
    {
      name: 'Access Level',
      description: 'Private: restricted access to specific apps. Public: accessible to all developers. Internal: internal use only.',
      format: 'private | public | internal',
    },
    {
      name: 'Authorized Paths (customization)',
      description: 'You can add, modify, or remove paths. Use /** to authorize all sub-paths.',
      format: '/path/** or /path/specific',
    },
  ],
  tips: [
    'Use "Auto-generate from OpenAPI" to quickly create products segmented by path groups.',
    'The wildcard /** authorizes all sub-paths of a given prefix.',
    'Each environment can have a different product configuration.',
    'Path suggestions are based on groups detected in your OpenAPI.',
  ],
};

export const targetServersHelpContent = {
  title: 'Target Servers',
  description: 'Configure backend servers for each environment. Target Servers define where Apigee routes requests after processing. You can also configure KVMs (Key-Value Maps) to store sensitive configurations.',
  steps: [
    { number: 1, text: 'Select the environment tab to configure.' },
    { number: 2, text: 'The Target Path is automatically extracted from your OpenAPI.', isAutoGenerated: true },
    { number: 3, text: 'Enter the Host for each environment. If your OpenAPI contains multiple servers, they are auto-filled.', isAutoGenerated: true },
    { number: 4, text: 'Configure the port (443 by default) and SSL options.' },
    { number: 5, text: 'Fill in KVM values for any URL variables detected in your OpenAPI servers.' },
  ],
  autoGeneratedFields: [
    {
      name: 'Target Server Name',
      description: 'Automatically generated from the entity, backend apps and version: {entity}.{backendApps}.{version}.backend',
      example: 'elis.erp-sap.v1.backend',
    },
    {
      name: 'Target Path',
      description: 'Path extracted from the server defined in your OpenAPI. Automatically added to requests going to the backend.',
      example: '/DebtCollection',
    },
    {
      name: 'Host (if detected)',
      description: 'If your OpenAPI defines multiple servers with environment naming patterns (dev, staging, prod), hosts are automatically mapped.',
      example: 'api-dev.example.com',
    },
    {
      name: 'Port',
      description: 'Default is 443 for HTTPS. Can be extracted from the server URL if specified.',
    },
    {
      name: 'Variables in Target Path',
      description: 'If your OpenAPI server URL contains template variables like {customer} or {tenant}, they are converted to KVM references {private.backend_info_N}. A KVM entry is created for each variable, and you must fill in the value for each environment.',
      format: '{varName} → {private.backend_info_N}',
      example: '/{customer}/api → /{private.backend_info_1}/api',
    },
    {
      name: 'Multiple Server URLs',
      description: 'If your OpenAPI defines multiple servers with different paths, the varying segment is extracted and stored in a KVM entry. Values are auto-detected based on environment names in the URLs.',
      example: '/dev/api vs /prod/api → /{private.backend_info_1}/api',
    },
  ],
  manualFields: [
    {
      name: 'Host',
      description: 'The hostname or IP of your backend server for this environment. Each environment typically has a different host. If your OpenAPI defines multiple servers, hosts are mapped per environment automatically.',
      format: 'hostname or IP',
      example: 'services-test.sveafinans.no',
    },
    {
      name: 'Port',
      description: 'The port of the backend server. 443 for HTTPS, 80 for HTTP.',
      format: 'number',
      example: '443',
    },
    {
      name: 'SSL Enabled',
      description: 'Enables HTTPS communication to the backend. Recommended for production.',
    },
    {
      name: 'Client Auth Enabled',
      description: 'Enables mutual TLS authentication (mTLS). Requires a client certificate.',
    },
    {
      name: 'KVM (Key-Value Maps)',
      description: 'Secure storage for credentials, tokens, or sensitive configurations. Values are encrypted in Apigee.',
      example: 'my-api.v1.credentials with username/password keys',
    },
    {
      name: 'Backend Info Values',
      description: 'When URL variables are detected, you must fill in the value for each backend_info entry per environment. These values replace the {private.backend_info_N} placeholders at runtime.',
      format: 'Value per environment',
      example: 'backend_info_1: dev1="dev", prod1="prod"',
    },
  ],
  tips: [
    'KVMs are ideal for securely storing backend authentication credentials.',
    'Each environment must have its own host configured.',
    'Always enable SSL for production environments.',
    'The Target Path is automatically added to all requests going to the backend.',
    'URL variables like {env} are converted to {private.backend_info_N} and resolved from KVM at runtime.',
  ],
};

// URL Variabilization rules documentation
export const urlVariabilizationHelpContent = {
  title: 'URL Variabilization',
  description: 'When your OpenAPI servers contain template variables or environment-specific URLs, the system automatically creates KVM entries to store different values per environment.',
  steps: [
    { number: 1, text: 'Template variables like {env} or {customer} in server URLs are detected automatically.', isAutoGenerated: true },
    { number: 2, text: 'Each variable is converted to a KVM reference: {private.backend_info_N}', isAutoGenerated: true },
    { number: 3, text: 'Fill in the value for each environment in the KVM section below.' },
    { number: 4, text: 'At runtime, Apigee replaces the variable with the environment-specific value from the KVM.' },
  ],
  autoGeneratedFields: [
    {
      name: 'Template Variables',
      description: 'Variables like {env}, {customer}, {tenant} in your OpenAPI server URLs are automatically detected and converted to backend_info KVM entries.',
      format: '{variableName} → {private.backend_info_N}',
      example: '{customer}/api → {private.backend_info_1}/api',
    },
    {
      name: 'Path Differences',
      description: 'When multiple server URLs have different path segments, the varying part is extracted and stored in a KVM entry.',
      example: '/dev/api vs /prod/api → {private.backend_info_1}/api',
    },
    {
      name: 'Host Mapping',
      description: 'When multiple server URLs have different hosts, each host is mapped to its corresponding environment (dev1, uat1, staging, prod1).',
      example: 'api-dev.example.com → dev1, api.example.com → prod1',
    },
  ],
  manualFields: [
    {
      name: 'KVM Values per Environment',
      description: 'For each detected variable, you must provide a value for each environment. These values replace the {private.backend_info_N} placeholders at runtime.',
      format: 'String value per environment',
      example: 'dev1: "dev", uat1: "test", staging: "preprod", prod1: "prod"',
    },
  ],
  tips: [
    'Variables in host: the host itself varies per environment (configured in Target Server Host field).',
    'Variables in path: stored in KVM and resolved at runtime using {private.backend_info_N}.',
    'The backend-info KVM is automatically created with entries for each detected variable.',
    'Values are encrypted in Apigee when stored in KVMs.',
  ],
};
