import React from 'react';
import { X, Sparkles, FileText, CheckCircle } from 'lucide-react';
import { cn } from '@/lib/utils';

interface HelpStep {
  number: number;
  text: string;
  isAutoGenerated?: boolean;
}

interface HelpField {
  name: string;
  description: string;
  isAutoGenerated?: boolean;
  format?: string;
  example?: string;
}

interface HelpPanelProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  description: string;
  steps?: HelpStep[];
  autoGeneratedFields?: HelpField[];
  manualFields?: HelpField[];
  tips?: string[];
}

export const HelpPanel: React.FC<HelpPanelProps> = ({
  isOpen,
  onClose,
  title,
  description,
  steps,
  autoGeneratedFields,
  manualFields,
  tips,
}) => {
  return (
    <>
      {/* Backdrop */}
      <div
        className={cn(
          "fixed inset-0 bg-black/20 z-40 transition-opacity duration-300",
          isOpen ? "opacity-100" : "opacity-0 pointer-events-none"
        )}
        onClick={onClose}
      />

      {/* Panel */}
      <div
        className={cn(
          "fixed top-0 right-0 h-full w-[420px] bg-[var(--swiss-white)] border-l-2 border-[var(--swiss-black)] z-50 overflow-y-auto transition-transform duration-300 ease-out swiss-scroll",
          isOpen ? "translate-x-0" : "translate-x-full"
        )}
      >
        {/* Header */}
        <div className="sticky top-0 bg-[var(--swiss-black)] text-[var(--swiss-white)] px-6 py-5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-[var(--swiss-white)] rounded flex items-center justify-center">
                <FileText className="w-4 h-4 text-[var(--swiss-black)]" />
              </div>
              <span className="text-xs font-black uppercase tracking-widest">Guide</span>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/10 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 pb-24 space-y-6">
          {/* Title & Description */}
          <div>
            <h2 className="text-lg font-black mb-2">{title}</h2>
            <p className="text-sm text-[var(--swiss-gray-600)] leading-relaxed">
              {description}
            </p>
          </div>

          {/* Steps */}
          {steps && steps.length > 0 && (
            <div>
              <h3 className="text-[10px] font-black uppercase tracking-widest text-[var(--swiss-gray-400)] mb-3 pb-2 border-b border-[var(--swiss-gray-100)]">
                How to Use
              </h3>
              <div className="space-y-3">
                {steps.map((step) => (
                  <div key={step.number} className="flex gap-3">
                    <div className="w-6 h-6 bg-[var(--swiss-gray-100)] text-[var(--swiss-gray-600)] rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0">
                      {step.number}
                    </div>
                    <div className="flex-1">
                      <p className="text-sm text-[var(--swiss-gray-700)]">{step.text}</p>
                      {step.isAutoGenerated && (
                        <span className="inline-flex items-center gap-1 mt-1 text-[10px] text-amber-600">
                          <Sparkles className="w-3 h-3" /> Auto-filled
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Auto-generated Fields */}
          {autoGeneratedFields && autoGeneratedFields.length > 0 && (
            <div>
              <h3 className="text-[10px] font-black uppercase tracking-widest text-[var(--swiss-gray-400)] mb-3 pb-2 border-b border-[var(--swiss-gray-100)] flex items-center gap-2">
                <Sparkles className="w-3 h-3 text-amber-500" />
                Auto-filled Fields
              </h3>
              <div className="space-y-4">
                {autoGeneratedFields.map((field, index) => (
                  <div key={index} className="bg-amber-50/50 border-l-2 border-amber-400 pl-3 py-2">
                    <p className="text-xs font-bold text-[var(--swiss-gray-800)] mb-1">{field.name}</p>
                    <p className="text-xs text-[var(--swiss-gray-600)] leading-relaxed">{field.description}</p>
                    {field.format && (
                      <p className="text-[10px] font-mono text-[var(--swiss-gray-500)] mt-1">
                        Format: <span className="text-[var(--swiss-black)]">{field.format}</span>
                      </p>
                    )}
                    {field.example && (
                      <p className="text-[10px] font-mono bg-[var(--swiss-gray-100)] px-2 py-1 mt-1 inline-block">
                        {field.example}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Manual Fields */}
          {manualFields && manualFields.length > 0 && (
            <div>
              <h3 className="text-[10px] font-black uppercase tracking-widest text-[var(--swiss-gray-400)] mb-3 pb-2 border-b border-[var(--swiss-gray-100)]">
                Fields to Fill Manually
              </h3>
              <div className="space-y-4">
                {manualFields.map((field, index) => (
                  <div key={index} className="border-l-2 border-[var(--swiss-gray-200)] pl-3 py-2">
                    <p className="text-xs font-bold text-[var(--swiss-gray-800)] mb-1">{field.name}</p>
                    <p className="text-xs text-[var(--swiss-gray-600)] leading-relaxed">{field.description}</p>
                    {field.format && (
                      <p className="text-[10px] font-mono text-[var(--swiss-gray-500)] mt-1">
                        Format: <span className="text-[var(--swiss-black)]">{field.format}</span>
                      </p>
                    )}
                    {field.example && (
                      <p className="text-[10px] font-mono bg-[var(--swiss-gray-100)] px-2 py-1 mt-1 inline-block">
                        {field.example}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Tips */}
          {tips && tips.length > 0 && (
            <div>
              <h3 className="text-[10px] font-black uppercase tracking-widest text-[var(--swiss-gray-400)] mb-3 pb-2 border-b border-[var(--swiss-gray-100)]">
                Tips
              </h3>
              <div className="space-y-2">
                {tips.map((tip, index) => (
                  <div key={index} className="flex gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />
                    <p className="text-xs text-[var(--swiss-gray-600)]">{tip}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default HelpPanel;
